/* AUTO-GENERATED by scripts/sync-stripe-catalog.mjs — do not edit by hand. */
/* mode: live | syncedAt: 2026-09-21T09:23:46.143Z */

export type StripeCatalogPrice = {
  productId: string;
  priceId: string;
  amountUsd: number;
  label: string;
};

export type StripeCatalog = {
  mode: "test" | "live";
  syncedAt: string;
  memberships: Record<
    string,
    Record<string, Partial<Record<"month" | "year", StripeCatalogPrice>>>
  >;
  alaCarte: Record<string, StripeCatalogPrice>;
  creditPacks: Record<string, StripeCatalogPrice>;
};

export const STRIPE_CATALOG: StripeCatalog = {
  "mode": "live",
  "syncedAt": "2026-09-21T09:23:46.143Z",
  "memberships": {
    "starter": {
      "adult": {
        "month": {
          "productId": "prod_VDNW0LfJcitlzh",
          "priceId": "price_1UI3RwJOsDH7RgBdbO0wCM7A",
          "amountUsd": 117,
          "label": "Starter Adults Every 3 months"
        },
        "year": {
          "productId": "prod_VDNW0LfJcitlzh",
          "priceId": "price_1UCwltJOsDH7RgBdkmL2tUs7",
          "amountUsd": 390,
          "label": "Starter Adults Yearly"
        }
      },
      "senior": {
        "month": {
          "productId": "prod_VDNWkxCGzGfWPv",
          "priceId": "price_1UI3RyJOsDH7RgBdRJ8bpeLa",
          "amountUsd": 102,
          "label": "Starter Seniors (50+) Every 3 months"
        },
        "year": {
          "productId": "prod_VDNWkxCGzGfWPv",
          "priceId": "price_1UCwluJOsDH7RgBd3OF30miM",
          "amountUsd": 340,
          "label": "Starter Seniors (50+) Yearly"
        }
      }
    },
    "pro": {
      "adult": {
        "month": {
          "productId": "prod_VDNXXVVfjFcIDZ",
          "priceId": "price_1UI3S0JOsDH7RgBdM4h0LeHt",
          "amountUsd": 207,
          "label": "Pro Adults Every 3 months"
        },
        "year": {
          "productId": "prod_VDNXXVVfjFcIDZ",
          "priceId": "price_1UCwlwJOsDH7RgBdhjUAfxBt",
          "amountUsd": 690,
          "label": "Pro Adults Yearly"
        }
      },
      "senior": {
        "month": {
          "productId": "prod_VDNXp0qkSHjoSk",
          "priceId": "price_1UI3S1JOsDH7RgBdBcY2Ng7A",
          "amountUsd": 171,
          "label": "Pro Seniors (50+) Every 3 months"
        },
        "year": {
          "productId": "prod_VDNXp0qkSHjoSk",
          "priceId": "price_1UCwlyJOsDH7RgBdVke8Hlat",
          "amountUsd": 570,
          "label": "Pro Seniors (50+) Yearly"
        }
      }
    },
    "elite": {
      "adult": {
        "month": {
          "productId": "prod_VDNXrXI9JxygaK",
          "priceId": "price_1UI3S3JOsDH7RgBdPElJJOmz",
          "amountUsd": 357,
          "label": "Elite Adults Every 3 months"
        },
        "year": {
          "productId": "prod_VDNXrXI9JxygaK",
          "priceId": "price_1UCwlzJOsDH7RgBdtGmSSCvN",
          "amountUsd": 1190,
          "label": "Elite Adults Yearly"
        }
      },
      "senior": {
        "month": {
          "productId": "prod_VDNXLOrg53RF4w",
          "priceId": "price_1UI3S5JOsDH7RgBdFgMLwljy",
          "amountUsd": 282,
          "label": "Elite Seniors (50+) Every 3 months"
        },
        "year": {
          "productId": "prod_VDNXLOrg53RF4w",
          "priceId": "price_1UCwm1JOsDH7RgBdOpehWSJP",
          "amountUsd": 940,
          "label": "Elite Seniors (50+) Yearly"
        }
      }
    }
  },
  "alaCarte": {
    "story-time": {
      "productId": "prod_VDNX7befOMeKpO",
      "priceId": "price_1UCwm1JOsDH7RgBd6XxB8C3S",
      "amountUsd": 15,
      "label": "Kevina Starr Story Time (1 session)"
    },
    "junior-lab": {
      "productId": "prod_VDNXuCtqGPDQFz",
      "priceId": "price_1UCwm2JOsDH7RgBdHn1j9zz4",
      "amountUsd": 25,
      "label": "Teens Glow Lab seat"
    },
    "workshop-general": {
      "productId": "prod_VDNX8eSulyW2rG",
      "priceId": "price_1UDGE2JOsDH7RgBdFqqL6WlJ",
      "amountUsd": 40,
      "label": "Workshops (Starter & Above Workshops Free)"
    },
    "training-group": {
      "productId": "prod_VDNXNxUmhI5Lq7",
      "priceId": "price_1UCwm4JOsDH7RgBdnYXq9NnG",
      "amountUsd": 45,
      "label": "Group training session"
    },
    "consult-30": {
      "productId": "prod_VDNXJiYhLUMDh1",
      "priceId": "price_1UDGE4JOsDH7RgBdb7yXDUHA",
      "amountUsd": 45,
      "label": "1-on-1 consulting (30 min)"
    },
    "consult-60": {
      "productId": "prod_VDNXSnvWGFABjd",
      "priceId": "price_1UDGE5JOsDH7RgBdodAXL4Hb",
      "amountUsd": 65,
      "label": "1-on-1 consulting (60 min)"
    },
    "consult-90": {
      "productId": "prod_VDNX8SxP97UAtw",
      "priceId": "price_1UDGE6JOsDH7RgBd97N8HlvZ",
      "amountUsd": 75,
      "label": "1-on-1 consulting (90 min)"
    },
    "consult-120": {
      "productId": "prod_VDhdREd8BZUkr8",
      "priceId": "price_1UDGE7JOsDH7RgBd5zHdaZTQ",
      "amountUsd": 145,
      "label": "1-on-1 consulting (2 hours)"
    },
    "progress-pdf": {
      "productId": "prod_VDNXRq7xb34MOW",
      "priceId": "price_1UCwm8JOsDH7RgBdtgXh7Z8S",
      "amountUsd": 12,
      "label": "Progress report PDF (one-off)"
    },
    "zip-timing": {
      "productId": "prod_VDNX41zMFofRwy",
      "priceId": "price_1UCwm9JOsDH7RgBdY0e2YL7k",
      "amountUsd": 29,
      "label": "Best-times ZipCode scout (month)"
    }
  },
  "creditPacks": {
    "boost": {
      "productId": "prod_VDNXQljFOXQw9b",
      "priceId": "price_1UCwmAJOsDH7RgBdRj4rCO1E",
      "amountUsd": 5,
      "label": "Boost Pack (5 credits)"
    },
    "builder": {
      "productId": "prod_VDNXOxly6w9BXG",
      "priceId": "price_1UCwmBJOsDH7RgBdSRtOslnX",
      "amountUsd": 10,
      "label": "Builder Pack (10 credits)"
    },
    "launcher": {
      "productId": "prod_VDNXBXcUvaJ7AE",
      "priceId": "price_1UCwmCJOsDH7RgBdduUneqW7",
      "amountUsd": 20,
      "label": "Launcher Pack (20 credits)"
    },
    "family": {
      "productId": "prod_VDNXW6tfuZ9C4D",
      "priceId": "price_1UCwmDJOsDH7RgBd9wp3mnM4",
      "amountUsd": 40,
      "label": "Family Pack (40 credits)"
    }
  }
} as const;
