import { readFileSync } from 'node:fs';
import { resolve } from 'node:path';
import { describe, expect, it } from 'vitest';

function source(relativePath: string) {
  return readFileSync(resolve(process.cwd(), relativePath), 'utf8');
}

describe('home first section mockup', () => {
  it('keeps a proportional landscape hero with active Join and Shop hotspots', () => {
    const quote = source('src/components/HeaderQuoteBar.tsx');
    const hero = source('src/components/Hero.tsx');
    const header = source('src/components/Header.tsx');

    expect(quote).toContain('bg-[#FFEDD5]');
    expect(quote).toContain('Hot flash at 2pm.');
    expect(hero).toContain('data-testid="home-hero-bleed"');
    expect(hero).toContain('data-testid="home-hero-image"');
    expect(hero).toContain('homeHeroHotspotStyle');
    expect(hero).toContain('HOME_HERO_JOIN_HOTSPOT');
    expect(hero).toContain('HOME_HERO_SHOP_HOTSPOT');
    expect(hero).not.toContain('HeroCarousel');
    expect(hero).not.toContain('home-hero-carousel');
    expect(hero).toContain('MovementCarousel');
    expect(hero).toContain('home-movement');
    expect(hero).toContain('home-hero-shot');
    expect(hero).toContain('home-hero-frame');
    expect(hero).toContain('sm:grid-cols-[minmax(0,1fr)_11.5rem]');
    expect(hero).not.toContain('max-w-6xl');
    expect(hero).not.toContain('max-w-5xl');
    expect(hero.indexOf('home-hero-bleed')).toBeLessThan(hero.indexOf('home-pillars'));
    expect(hero.indexOf('home-pillars')).toBeLessThan(hero.indexOf('id="mood-tool"'));
    expect((hero.match(/id="mood-tool"/g) ?? []).length).toBe(1);
    expect((hero.match(/data-testid="home-mood-rail"/g) ?? []).length).toBe(1);
    expect(hero).toContain('sm:row-span-2');
    expect(hero).not.toContain('sm:col-span-2');
    expect(hero.indexOf('home-pillars')).toBeLessThan(hero.indexOf('home-movement'));
    expect(hero).toContain('home-cta-explore');
    expect(hero).toContain('home-cta-shop');
    expect(hero).toContain('HOME_HERO_SHOP_HREF');
    expect(hero).toContain('href={HOME_HERO_SHOP_HREF}');
    expect(hero).toContain('onNavigateToGear');
    expect(hero.indexOf('home-cta-shop')).toBeGreaterThan(hero.indexOf('home-cta-explore'));
    expect(hero).toContain('home-pillars');
    expect(hero).toContain('home-pillar-rail');
    expect(hero).toContain('home-pillar-script');
    expect(hero).toMatch(/home-pillar-script[^"]*block/);
    expect(hero).not.toMatch(/home-pillar-script[^"]*hidden sm:block/);
    expect(source('src/index.css')).toContain('object-fit: contain');
    expect(source('src/index.css')).not.toContain('min(42vh');
    expect(source('src/index.css')).not.toContain('min(44vh');
    expect(source('src/index.css')).not.toMatch(/\.home-hero-shot img \{[\s\S]*object-fit: cover/);
    expect(source('src/index.css').trimEnd().endsWith('}')).toBe(true);
    expect(hero).toContain('homePillarDisplay');
    expect(hero).toContain('FancySectionHeading');
    expect(hero).toContain('homeMoodLabelDisplay');
    expect(hero).toContain('home-mood-label');
    expect(hero).toContain('grid-cols-2 sm:grid-cols-3 md:grid-cols-6');
    expect(source('src/index.css')).toContain('.home-mood-label');
    expect(source('src/index.css')).toMatch(/\.home-mood-label \{[\s\S]*font-size: 0\.72rem/);
    expect(hero).toContain('home-pillar-rail');
    expect(hero).toContain('border-t-2');
    expect(hero).toContain('sm:border-t-[16px]');
    expect(hero).toContain('homeMovementTitleDisplay');
    expect(hero).toContain('items-stretch');
    expect(hero).toContain('DailyAffirmationsWidget');
    expect(hero).toContain('canManageMovementCarousel');
    expect(hero).toContain('home-website-links');
    expect(hero).toContain('home-website-link-${id}');
    expect(hero).toContain('HOME_WEBSITE_LINK_IDS');
    expect(hero).toContain('pt-6');
    expect(hero).toContain('md:pt-0');
    expect(hero.indexOf('DailyAffirmationsWidget')).toBeLessThan(hero.indexOf('home-movement-cta'));
    expect(hero).toContain('home-who-won-today');
    expect(hero).toContain('HOME_WHO_WON_TODAY_LABEL');
    expect(hero).toContain('HOME_WHO_WON_TODAY_TARGET');
    expect(hero).toContain('{HOME_WHO_WON_TODAY_LABEL}');
    expect(hero).toContain('ArrowDown');
    expect(hero).not.toContain('<Receipt');
    expect(hero).toContain('HOME_WHO_WON_TODAY_POP_CLASS');
    expect(hero.indexOf('home-movement-title')).toBeLessThan(hero.indexOf('home-who-won-today'));
    expect(hero).toContain('home-join-movement');
    expect(hero).toContain("onScrollToSection('mailing-list')");
    expect(hero).not.toContain('home-copy-edit');
    expect(hero).not.toContain('HomeEditableField');
    expect(header).toContain('HeaderQuoteBar');
    expect(header.indexOf('HeaderQuoteBar')).toBeLessThan(header.indexOf('site-header-brand'));
    expect(header.indexOf('header-desktop-account')).toBeLessThan(header.indexOf('site-header-brand'));
    expect(header.indexOf('header-desktop-sign-in')).toBeLessThan(header.indexOf('site-header-brand'));
    expect(header.indexOf('site-header-brand')).toBeLessThan(header.indexOf('header-nav-home'));
    expect(header).toContain('md:px-4');
    expect(header).toContain('data-testid="site-header-spacer"');
    expect(header).toContain('HEADER_DESKTOP_SPACER_CLASS');
    expect(header).toContain('{GEAR_SHOP_LABEL}');
    expect(header).toContain('data-testid="header-shop-menu"');
    expect(header).toContain('header-shop-menu-gear');
    expect(header).toContain('header-shop-planners');
    expect((header.match(/data-testid="header-nav-affirmations"/g) ?? []).length).toBe(1);
    expect((header.match(/data-testid="header-nav-challenge"/g) ?? []).length).toBe(1);
    expect(header).toContain('HEADER_TRAILING_LINKS.map');
    expect(header).toContain('header-nav-${link.route}');
    expect(header.indexOf('header-nav-home')).toBeLessThan(header.indexOf('HEADER_TRAILING_LINKS.map'));
    expect(header.indexOf('HEADER_TRAILING_LINKS.map')).toBeLessThan(header.indexOf('header-nav-affirmations'));
    expect(header.indexOf('header-nav-affirmations')).toBeLessThan(header.indexOf('header-nav-challenge'));
    expect(header.indexOf('header-nav-challenge')).toBeLessThan(header.indexOf('header-shop-menu'));
    expect(header.indexOf('header-shop-menu')).toBeLessThan(header.indexOf('header-join-movement'));
    expect(header).not.toContain('header-nav-mood');
    expect(header).not.toContain('header-nav-receipts');
    expect(header).not.toMatch(/>[\s]*Shop[\s]*</);
    expect(header).toContain('Join the Movement');
    expect(header).toContain('onOpenJoin');
    expect(header.indexOf('header-nav-challenge')).toBeLessThan(header.indexOf('header-join-movement'));
    expect(header).toMatch(/data-testid="header-join-movement"[\s\S]*ComingSoonBadge/);
    expect(header).not.toContain("onNavigate('list')");
  });

  it('keeps What Won Today close to Join the Movement with a subtle separator', () => {
    const receipts = source('src/components/ReceiptBuilder.tsx');
    const intro = source('src/components/WebsiteIntroSection.tsx');

    expect(receipts).toContain('data-testid="receipts-section-separator"');
    expect(receipts).toContain('bg-[#E8C49A]');
    expect(receipts).toContain('pt-4');
    expect(receipts).toContain('sm:pt-5');
    expect(receipts).not.toContain('sm:py-16');
    expect(receipts).toContain('FancySectionHeading');
    expect(receipts).toContain('homeReceiptsTitleDisplay');
    expect(receipts).toContain('receipts-heading');
    expect(receipts).not.toContain('WHAT WON TODAY? (PLAN RECEIPTS)');
    expect(receipts).not.toContain('font-serif');
    expect(intro).toContain('pb-3');
    expect(intro).toContain('sm:pb-4');
    expect(intro).not.toContain('sm:py-8');
  });
});
