SELECT case_id, assignee
FROM test_case_status
WHERE case_id LIKE 'GUIDE-REV-%airbnb-cohost'
   OR case_id LIKE 'GUIDE-REV-%community-newsletter-creator'
   OR case_id LIKE 'GUIDE-REV-%consulting'
   OR case_id LIKE 'GUIDE-REV-%flipping-properties'
   OR case_id LIKE 'GUIDE-REV-%google-business-helper'
   OR case_id LIKE 'GUIDE-REV-%junior-content-create'
   OR case_id LIKE 'GUIDE-REV-%lien-tax-sales'
   OR case_id LIKE 'GUIDE-REV-%local-business-ai-setup'
   OR case_id LIKE 'GUIDE-REV-%notary'
   OR case_id LIKE 'GUIDE-REV-%resume-linkedin-helper'
   OR case_id LIKE 'GUIDE-REV-%review-response-assistant'
   OR case_id LIKE 'GUIDE-REV-%short-form-video-editor'
   OR case_id LIKE 'GUIDE-REV-%social'
   OR case_id LIKE 'GUIDE-REV-%start-gardening-club'
   OR case_id LIKE 'GUIDE-REV-%teaching'
   OR case_id LIKE 'GUIDE-REV-%travel-research-assistant'
   OR case_id LIKE 'GUIDE-REV-%ugc-creator'
   OR case_id LIKE 'GUIDE-REV-%virtual-assistant'
   OR case_id LIKE 'GUIDE-REV-%virtual-call-assistant'
   OR case_id LIKE 'GUIDE-REV-%virtual-receptionist'
   OR case_id LIKE 'GUIDE-REV-%web-leads'
   OR case_id LIKE 'GUIDE-REV-%website-tester'
ORDER BY case_id;
