-- Assign unassigned Guide Library guides to Evelyn. Do not change published/minTier.
UPDATE guide_catalog_state
SET patch_json = json_patch(
      CASE WHEN json_valid(patch_json) THEN patch_json ELSE '{}' END,
      '{"assignee":"evelyn"}'
    ),
    updated_at = '2026-09-13T01:05:00.000Z',
    updated_by = 'Evelyn Irving'
WHERE guide_id IN (
  'airbnb-cohost',
  'community-newsletter-creator',
  'consulting',
  'flipping-properties',
  'google-business-helper',
  'junior-content-create',
  'lien-tax-sales',
  'local-business-ai-setup',
  'notary',
  'resume-linkedin-helper',
  'review-response-assistant',
  'short-form-video-editor',
  'social',
  'start-gardening-club',
  'teaching',
  'travel-research-assistant',
  'ugc-creator',
  'virtual-assistant',
  'virtual-call-assistant',
  'virtual-receptionist',
  'web-leads',
  'website-tester'
)
AND (
  json_extract(patch_json, '$.assignee') IS NULL
  OR trim(COALESCE(json_extract(patch_json, '$.assignee'), '')) = ''
  OR lower(trim(COALESCE(json_extract(patch_json, '$.assignee'), ''))) IN ('unassigned')
);

UPDATE test_case_status
SET assignee = 'evelyn',
    updated_at = '2026-09-13T01:05:00.000Z',
    updated_by = 'Evelyn Irving'
WHERE case_id IN (
  'GUIDE-REV-launch-airbnb-cohost',
  'GUIDE-REV-kids-airbnb-cohost',
  'GUIDE-REV-junior-airbnb-cohost',
  'GUIDE-REV-senior-airbnb-cohost',
  'GUIDE-REV-launch-community-newsletter-creator',
  'GUIDE-REV-kids-community-newsletter-creator',
  'GUIDE-REV-junior-community-newsletter-creator',
  'GUIDE-REV-senior-community-newsletter-creator',
  'GUIDE-REV-launch-consulting',
  'GUIDE-REV-kids-consulting',
  'GUIDE-REV-junior-consulting',
  'GUIDE-REV-senior-consulting',
  'GUIDE-REV-launch-flipping-properties',
  'GUIDE-REV-kids-flipping-properties',
  'GUIDE-REV-junior-flipping-properties',
  'GUIDE-REV-senior-flipping-properties',
  'GUIDE-REV-launch-google-business-helper',
  'GUIDE-REV-kids-google-business-helper',
  'GUIDE-REV-junior-google-business-helper',
  'GUIDE-REV-senior-google-business-helper',
  'GUIDE-REV-launch-junior-content-create',
  'GUIDE-REV-kids-junior-content-create',
  'GUIDE-REV-junior-junior-content-create',
  'GUIDE-REV-senior-junior-content-create',
  'GUIDE-REV-launch-lien-tax-sales',
  'GUIDE-REV-kids-lien-tax-sales',
  'GUIDE-REV-junior-lien-tax-sales',
  'GUIDE-REV-senior-lien-tax-sales',
  'GUIDE-REV-launch-local-business-ai-setup',
  'GUIDE-REV-kids-local-business-ai-setup',
  'GUIDE-REV-junior-local-business-ai-setup',
  'GUIDE-REV-senior-local-business-ai-setup',
  'GUIDE-REV-launch-notary',
  'GUIDE-REV-kids-notary',
  'GUIDE-REV-junior-notary',
  'GUIDE-REV-senior-notary',
  'GUIDE-REV-launch-resume-linkedin-helper',
  'GUIDE-REV-kids-resume-linkedin-helper',
  'GUIDE-REV-junior-resume-linkedin-helper',
  'GUIDE-REV-senior-resume-linkedin-helper',
  'GUIDE-REV-launch-review-response-assistant',
  'GUIDE-REV-kids-review-response-assistant',
  'GUIDE-REV-junior-review-response-assistant',
  'GUIDE-REV-senior-review-response-assistant',
  'GUIDE-REV-launch-short-form-video-editor',
  'GUIDE-REV-kids-short-form-video-editor',
  'GUIDE-REV-junior-short-form-video-editor',
  'GUIDE-REV-senior-short-form-video-editor',
  'GUIDE-REV-launch-social',
  'GUIDE-REV-kids-social',
  'GUIDE-REV-junior-social',
  'GUIDE-REV-senior-social',
  'GUIDE-REV-launch-start-gardening-club',
  'GUIDE-REV-kids-start-gardening-club',
  'GUIDE-REV-junior-start-gardening-club',
  'GUIDE-REV-senior-start-gardening-club',
  'GUIDE-REV-launch-teaching',
  'GUIDE-REV-kids-teaching',
  'GUIDE-REV-junior-teaching',
  'GUIDE-REV-senior-teaching',
  'GUIDE-REV-launch-travel-research-assistant',
  'GUIDE-REV-kids-travel-research-assistant',
  'GUIDE-REV-junior-travel-research-assistant',
  'GUIDE-REV-senior-travel-research-assistant',
  'GUIDE-REV-launch-ugc-creator',
  'GUIDE-REV-kids-ugc-creator',
  'GUIDE-REV-junior-ugc-creator',
  'GUIDE-REV-senior-ugc-creator',
  'GUIDE-REV-launch-virtual-assistant',
  'GUIDE-REV-kids-virtual-assistant',
  'GUIDE-REV-junior-virtual-assistant',
  'GUIDE-REV-senior-virtual-assistant',
  'GUIDE-REV-launch-virtual-call-assistant',
  'GUIDE-REV-kids-virtual-call-assistant',
  'GUIDE-REV-junior-virtual-call-assistant',
  'GUIDE-REV-senior-virtual-call-assistant',
  'GUIDE-REV-launch-virtual-receptionist',
  'GUIDE-REV-kids-virtual-receptionist',
  'GUIDE-REV-junior-virtual-receptionist',
  'GUIDE-REV-senior-virtual-receptionist',
  'GUIDE-REV-launch-web-leads',
  'GUIDE-REV-kids-web-leads',
  'GUIDE-REV-junior-web-leads',
  'GUIDE-REV-senior-web-leads',
  'GUIDE-REV-launch-website-tester',
  'GUIDE-REV-kids-website-tester',
  'GUIDE-REV-junior-website-tester',
  'GUIDE-REV-senior-website-tester'
);
