/** Adult / partner training circles for GYSH */

export type TrainingCircle = {
  id: string;
  name: string;
  blurb: string;
  audience: "adult" | "junior" | "all";
  level: "Beginner" | "Intermediate" | "Advanced";
  icon: string;
  accent: string;
};

export const TRAINING_CIRCLES: TrainingCircle[] = [
  {
    id: "dropshipping",
    name: "Dropshipping",
    blurb: "Store setup, supplier vetting, ad creative, and fulfillment ops without holding inventory.",
    audience: "adult",
    level: "Intermediate",
    icon: "📦",
    accent: "#9B2F28",
  },
  {
    id: "pod",
    name: "Print-on-Demand",
    blurb: "Design → Printify/Etsy/Shopify pipelines, niche research, and evergreen listing SEO.",
    audience: "adult",
    level: "Beginner",
    icon: "👕",
    accent: "#947D64",
  },
  {
    id: "agents",
    name: "Creating AI Agents",
    blurb: "Build custom agents the Muntie Ev way — soul, identity, memory, and plain-English orchestration.",
    audience: "adult",
    level: "Advanced",
    icon: "🤖",
    accent: "#D7C697",
  },
  {
    id: "prompting",
    name: "AI Prompting",
    blurb: "Prompt patterns for research, copy, image briefs, and agent command panels that actually ship.",
    audience: "adult",
    level: "Beginner",
    icon: "✨",
    accent: "#b8943d",
  },
  {
    id: "apps",
    name: "Building Applications",
    blurb: "From idea → Antigravity / Cursor workflows → working apps with auth, data, and deploy.",
    audience: "adult",
    level: "Advanced",
    icon: "🛠️",
    accent: "#9B2F28",
  },
  {
    id: "websites",
    name: "Building Websites",
    blurb: "Brand sites, landing pages, and Cloudflare Pages deploys that convert — GYSH-style.",
    audience: "adult",
    level: "Intermediate",
    icon: "🌐",
    accent: "#947D64",
  },
  {
    id: "airbnb",
    name: "Airbnb & STR Ops",
    blurb: "Arbitrage legality, furnishing budgets, dynamic pricing, and guest messaging systems.",
    audience: "adult",
    level: "Intermediate",
    icon: "🏠",
    accent: "#D7C697",
  },
  {
    id: "meta-shopify",
    name: "Meta Ads + Shopify",
    blurb: "Ad account hygiene, creative testing, and kill/hold/scale calls against real Shopify P&L.",
    audience: "adult",
    level: "Advanced",
    icon: "📊",
    accent: "#9B2F28",
  },
  {
    id: "product-research",
    name: "Product Research Scout",
    blurb: "Validate winners before you spend — trends, suppliers, reviews, and competitor ad intel.",
    audience: "adult",
    level: "Intermediate",
    icon: "🔍",
    accent: "#947D64",
  },
  {
    id: "affiliate",
    name: "Affiliate & Content Funnels",
    blurb: "SEO content hubs, SaaS recurring offers, and trust-first review systems.",
    audience: "adult",
    level: "Beginner",
    icon: "🔗",
    accent: "#b8943d",
  },
  {
    id: "automation",
    name: "Automation & Antigravity",
    blurb: "PM → Engineer → QA → DevOps pipelines so agents ship while you sleep.",
    audience: "adult",
    level: "Advanced",
    icon: "⚙️",
    accent: "#D7C697",
  },
  {
    id: "kids-glow",
    name: "Kids Glow & Junior Earnings",
    blurb: "Kevina Starr Stories + safe junior hustles — confidence first, then pocket money skills.",
    audience: "junior",
    level: "Beginner",
    icon: "🌟",
    accent: "#9B2F28",
  },
  {
    id: "web-leads",
    name: "Local Website Leads",
    blurb: "Map audits, outreach scripts, and done-for-you site packages for nearby businesses.",
    audience: "adult",
    level: "Intermediate",
    icon: "📍",
    accent: "#947D64",
  },
  {
    id: "ai-assets",
    name: "AI Asset Studio",
    blurb: "Productized logo/creative kits with AI — taste, delivery folders, and client retainers.",
    audience: "adult",
    level: "Beginner",
    icon: "🎨",
    accent: "#D7C697",
  },
  {
    id: "property-mgmt",
    name: "Property Management",
    blurb: "STR/LTR fee models, vendor benches, and owner reporting that complements Airbnb ops.",
    audience: "adult",
    level: "Intermediate",
    icon: "🔑",
    accent: "#9B2F28",
  },
  {
    id: "gigs",
    name: "Rideshare & Delivery Gigs",
    blurb: "Uber/Lyft + DoorDash/Eats shift planning, cost tracking, and peak-window discipline.",
    audience: "adult",
    level: "Beginner",
    icon: "🚗",
    accent: "#b8943d",
  },
  {
    id: "ai-timing",
    name: "AI Timing Scout",
    blurb: "ZIP-level hotspot briefs for drivers — events, weather, and sellable weekly playbooks.",
    audience: "adult",
    level: "Intermediate",
    icon: "🎯",
    accent: "#947D64",
  },
  {
    id: "book-publishing",
    name: "Book Publishing",
    blurb: "Tina's lane — manuscript to KDP/IngramSpark, covers, launch funnels, and royalties.",
    audience: "adult",
    level: "Intermediate",
    icon: "📚",
    accent: "#D7C697",
  },
];
