import { PlatformRegistryEntry } from './types';

export const SEEDED_PLATFORM_REGISTRY: PlatformRegistryEntry[] = [
  {
    id: 'youtube',
    display_name: 'YouTube',
    status: 'AVAILABLE',
    auth_method: 'OAUTH2',
    api_version: 'v3',
    capabilities: {
      has_views: true,
      has_likes: true,
      has_comments: true,
      has_shares: true,
      has_watch_time: true,
      has_retention_curve: true,
      has_swiped_away: false,
      has_traffic_sources: true,
      supports_historical_backfill: true,
      supports_realtime_polling: true,
      max_historical_days: 365,
      rate_limit_rpm: 60,
    },
    rate_limit_rpm: 60,
    doc_url: 'https://developers.google.com/youtube/v3',
  },
  {
    id: 'tiktok',
    display_name: 'TikTok',
    status: 'BETA',
    auth_method: 'OAUTH2',
    api_version: 'v2',
    capabilities: {
      has_views: true,
      has_likes: true,
      has_comments: true,
      has_shares: true,
      has_watch_time: true,
      has_retention_curve: false,
      has_swiped_away: true,
      has_traffic_sources: false,
      supports_historical_backfill: true,
      supports_realtime_polling: false,
      max_historical_days: 90,
      rate_limit_rpm: 30,
    },
    rate_limit_rpm: 30,
    doc_url: 'https://developers.tiktok.com/',
  },
  {
    id: 'facebook',
    display_name: 'Facebook',
    status: 'PLANNED',
    auth_method: 'OAUTH2',
    api_version: 'v18.0',
    capabilities: {
      has_views: true,
      has_likes: true,
      has_comments: true,
      has_shares: true,
      has_watch_time: true,
      has_retention_curve: false,
      has_swiped_away: false,
      has_traffic_sources: false,
      supports_historical_backfill: true,
      supports_realtime_polling: false,
      max_historical_days: 180,
      rate_limit_rpm: 60,
    },
    rate_limit_rpm: 60,
  },
  {
    id: 'instagram',
    display_name: 'Instagram',
    status: 'PLANNED',
    auth_method: 'OAUTH2',
    api_version: 'v18.0',
    capabilities: {
      has_views: true,
      has_likes: true,
      has_comments: true,
      has_shares: true,
      has_watch_time: false,
      has_retention_curve: false,
      has_swiped_away: false,
      has_traffic_sources: false,
      supports_historical_backfill: true,
      supports_realtime_polling: false,
      max_historical_days: 90,
      rate_limit_rpm: 60,
    },
    rate_limit_rpm: 60,
  },
  {
    id: 'x',
    display_name: 'X (Twitter)',
    status: 'PLANNED',
    auth_method: 'OAUTH2',
    api_version: 'v2',
    capabilities: {
      has_views: true,
      has_likes: true,
      has_comments: true,
      has_shares: true,
      has_watch_time: false,
      has_retention_curve: false,
      has_swiped_away: false,
      has_traffic_sources: false,
      supports_historical_backfill: false,
      supports_realtime_polling: true,
      max_historical_days: 30,
      rate_limit_rpm: 15,
    },
    rate_limit_rpm: 15,
  },
  {
    id: 'threads',
    display_name: 'Threads',
    status: 'PLANNED',
    auth_method: 'OAUTH2',
    capabilities: {
      has_views: true,
      has_likes: true,
      has_comments: true,
      has_shares: true,
      has_watch_time: false,
      has_retention_curve: false,
      has_swiped_away: false,
      has_traffic_sources: false,
      supports_historical_backfill: false,
      supports_realtime_polling: false,
      max_historical_days: 30,
      rate_limit_rpm: 30,
    },
    rate_limit_rpm: 30,
  },
  {
    id: 'linkedin',
    display_name: 'LinkedIn',
    status: 'PLANNED',
    auth_method: 'OAUTH2',
    capabilities: {
      has_views: true,
      has_likes: true,
      has_comments: true,
      has_shares: true,
      has_watch_time: false,
      has_retention_curve: false,
      has_swiped_away: false,
      has_traffic_sources: false,
      supports_historical_backfill: true,
      supports_realtime_polling: false,
      max_historical_days: 90,
      rate_limit_rpm: 30,
    },
    rate_limit_rpm: 30,
  },
  {
    id: 'pinterest',
    display_name: 'Pinterest',
    status: 'PLANNED',
    auth_method: 'OAUTH2',
    capabilities: {
      has_views: true,
      has_likes: false,
      has_comments: true,
      has_shares: true,
      has_watch_time: false,
      has_retention_curve: false,
      has_swiped_away: false,
      has_traffic_sources: false,
      supports_historical_backfill: true,
      supports_realtime_polling: false,
      max_historical_days: 90,
      rate_limit_rpm: 30,
    },
    rate_limit_rpm: 30,
  },
  {
    id: 'twitch',
    display_name: 'Twitch',
    status: 'PLANNED',
    auth_method: 'OAUTH2',
    capabilities: {
      has_views: true,
      has_likes: false,
      has_comments: true,
      has_shares: false,
      has_watch_time: true,
      has_retention_curve: false,
      has_swiped_away: false,
      has_traffic_sources: false,
      supports_historical_backfill: false,
      supports_realtime_polling: true,
      max_historical_days: 30,
      rate_limit_rpm: 60,
    },
    rate_limit_rpm: 60,
  },
  {
    id: 'reddit',
    display_name: 'Reddit',
    status: 'PLANNED',
    auth_method: 'OAUTH2',
    capabilities: {
      has_views: true,
      has_likes: true,
      has_comments: true,
      has_shares: true,
      has_watch_time: false,
      has_retention_curve: false,
      has_swiped_away: false,
      has_traffic_sources: false,
      supports_historical_backfill: true,
      supports_realtime_polling: false,
      max_historical_days: 30,
      rate_limit_rpm: 30,
    },
    rate_limit_rpm: 30,
  },
  {
    id: 'snapchat',
    display_name: 'Snapchat',
    status: 'PLANNED',
    auth_method: 'OAUTH2',
    capabilities: {
      has_views: true,
      has_likes: false,
      has_comments: false,
      has_shares: true,
      has_watch_time: true,
      has_retention_curve: false,
      has_swiped_away: true,
      has_traffic_sources: false,
      supports_historical_backfill: false,
      supports_realtime_polling: false,
      max_historical_days: 30,
      rate_limit_rpm: 30,
    },
    rate_limit_rpm: 30,
  },
];

export function getPlatformRegistryEntry(platformId: string): PlatformRegistryEntry | undefined {
  return SEEDED_PLATFORM_REGISTRY.find((p) => p.id === platformId);
}
