/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AgentRouteImport } from './routes/agent'
import { Route as AdvisorRouteImport } from './routes/advisor'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ScenarioNewRouteImport } from './routes/scenario.new'
import { Route as ScenarioCreatedCodeRouteImport } from './routes/scenario.created.$code'
import { Route as AgentScenarioCodeRouteImport } from './routes/agent.scenario.$code'
import { Route as AdvisorScenarioCodeRouteImport } from './routes/advisor.scenario.$code'

const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AgentRoute = AgentRouteImport.update({
  id: '/agent',
  path: '/agent',
  getParentRoute: () => rootRouteImport,
} as any)
const AdvisorRoute = AdvisorRouteImport.update({
  id: '/advisor',
  path: '/advisor',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ScenarioNewRoute = ScenarioNewRouteImport.update({
  id: '/scenario/new',
  path: '/scenario/new',
  getParentRoute: () => rootRouteImport,
} as any)
const ScenarioCreatedCodeRoute = ScenarioCreatedCodeRouteImport.update({
  id: '/scenario/created/$code',
  path: '/scenario/created/$code',
  getParentRoute: () => rootRouteImport,
} as any)
const AgentScenarioCodeRoute = AgentScenarioCodeRouteImport.update({
  id: '/scenario/$code',
  path: '/scenario/$code',
  getParentRoute: () => AgentRoute,
} as any)
const AdvisorScenarioCodeRoute = AdvisorScenarioCodeRouteImport.update({
  id: '/scenario/$code',
  path: '/scenario/$code',
  getParentRoute: () => AdvisorRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/advisor': typeof AdvisorRouteWithChildren
  '/agent': typeof AgentRouteWithChildren
  '/auth': typeof AuthRoute
  '/reset-password': typeof ResetPasswordRoute
  '/scenario/new': typeof ScenarioNewRoute
  '/advisor/scenario/$code': typeof AdvisorScenarioCodeRoute
  '/agent/scenario/$code': typeof AgentScenarioCodeRoute
  '/scenario/created/$code': typeof ScenarioCreatedCodeRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/advisor': typeof AdvisorRouteWithChildren
  '/agent': typeof AgentRouteWithChildren
  '/auth': typeof AuthRoute
  '/reset-password': typeof ResetPasswordRoute
  '/scenario/new': typeof ScenarioNewRoute
  '/advisor/scenario/$code': typeof AdvisorScenarioCodeRoute
  '/agent/scenario/$code': typeof AgentScenarioCodeRoute
  '/scenario/created/$code': typeof ScenarioCreatedCodeRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/advisor': typeof AdvisorRouteWithChildren
  '/agent': typeof AgentRouteWithChildren
  '/auth': typeof AuthRoute
  '/reset-password': typeof ResetPasswordRoute
  '/scenario/new': typeof ScenarioNewRoute
  '/advisor/scenario/$code': typeof AdvisorScenarioCodeRoute
  '/agent/scenario/$code': typeof AgentScenarioCodeRoute
  '/scenario/created/$code': typeof ScenarioCreatedCodeRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/advisor'
    | '/agent'
    | '/auth'
    | '/reset-password'
    | '/scenario/new'
    | '/advisor/scenario/$code'
    | '/agent/scenario/$code'
    | '/scenario/created/$code'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admin'
    | '/advisor'
    | '/agent'
    | '/auth'
    | '/reset-password'
    | '/scenario/new'
    | '/advisor/scenario/$code'
    | '/agent/scenario/$code'
    | '/scenario/created/$code'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/advisor'
    | '/agent'
    | '/auth'
    | '/reset-password'
    | '/scenario/new'
    | '/advisor/scenario/$code'
    | '/agent/scenario/$code'
    | '/scenario/created/$code'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRoute
  AdvisorRoute: typeof AdvisorRouteWithChildren
  AgentRoute: typeof AgentRouteWithChildren
  AuthRoute: typeof AuthRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  ScenarioNewRoute: typeof ScenarioNewRoute
  ScenarioCreatedCodeRoute: typeof ScenarioCreatedCodeRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/agent': {
      id: '/agent'
      path: '/agent'
      fullPath: '/agent'
      preLoaderRoute: typeof AgentRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/advisor': {
      id: '/advisor'
      path: '/advisor'
      fullPath: '/advisor'
      preLoaderRoute: typeof AdvisorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/scenario/new': {
      id: '/scenario/new'
      path: '/scenario/new'
      fullPath: '/scenario/new'
      preLoaderRoute: typeof ScenarioNewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/scenario/created/$code': {
      id: '/scenario/created/$code'
      path: '/scenario/created/$code'
      fullPath: '/scenario/created/$code'
      preLoaderRoute: typeof ScenarioCreatedCodeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/agent/scenario/$code': {
      id: '/agent/scenario/$code'
      path: '/scenario/$code'
      fullPath: '/agent/scenario/$code'
      preLoaderRoute: typeof AgentScenarioCodeRouteImport
      parentRoute: typeof AgentRoute
    }
    '/advisor/scenario/$code': {
      id: '/advisor/scenario/$code'
      path: '/scenario/$code'
      fullPath: '/advisor/scenario/$code'
      preLoaderRoute: typeof AdvisorScenarioCodeRouteImport
      parentRoute: typeof AdvisorRoute
    }
  }
}

interface AdvisorRouteChildren {
  AdvisorScenarioCodeRoute: typeof AdvisorScenarioCodeRoute
}

const AdvisorRouteChildren: AdvisorRouteChildren = {
  AdvisorScenarioCodeRoute: AdvisorScenarioCodeRoute,
}

const AdvisorRouteWithChildren =
  AdvisorRoute._addFileChildren(AdvisorRouteChildren)

interface AgentRouteChildren {
  AgentScenarioCodeRoute: typeof AgentScenarioCodeRoute
}

const AgentRouteChildren: AgentRouteChildren = {
  AgentScenarioCodeRoute: AgentScenarioCodeRoute,
}

const AgentRouteWithChildren = AgentRoute._addFileChildren(AgentRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRoute,
  AdvisorRoute: AdvisorRouteWithChildren,
  AgentRoute: AgentRouteWithChildren,
  AuthRoute: AuthRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  ScenarioNewRoute: ScenarioNewRoute,
  ScenarioCreatedCodeRoute: ScenarioCreatedCodeRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
