/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as VisitsRouteImport } from './routes/visits'
import { Route as UsersRouteImport } from './routes/users'
import { Route as UnsubscribeRouteImport } from './routes/unsubscribe'
import { Route as TestingRouteImport } from './routes/testing'
import { Route as TasksRouteImport } from './routes/tasks'
import { Route as StaffRouteImport } from './routes/staff'
import { Route as SourcesRouteImport } from './routes/sources'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as SitemapInternalDotxmlRouteImport } from './routes/sitemap-internal[.]xml'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as RegisterRouteImport } from './routes/register'
import { Route as QaManualRouteImport } from './routes/qa-manual'
import { Route as QaCreditsRouteImport } from './routes/qa-credits'
import { Route as QaRouteImport } from './routes/qa'
import { Route as PricingRouteImport } from './routes/pricing'
import { Route as NdaRouteImport } from './routes/nda'
import { Route as LegalRouteImport } from './routes/legal'
import { Route as LearningCenterRouteImport } from './routes/learning-center'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AgentRouteImport } from './routes/agent'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'
import { Route as StaffReportRouteImport } from './routes/staff_.report'
import { Route as ScenarioNewRouteImport } from './routes/scenario.new'
import { Route as ScenarioCodeRouteImport } from './routes/scenario.$code'
import { Route as LearningCenterSlugRouteImport } from './routes/learning-center_.$slug'
import { Route as EmailUnsubscribeRouteImport } from './routes/email/unsubscribe'
import { Route as AuthVerifyRouteImport } from './routes/auth.verify'
import { Route as AdminUsersRouteImport } from './routes/admin_.users'
import { Route as AdminStaffRouteImport } from './routes/admin_.staff'
import { Route as AdminPricingRouteImport } from './routes/admin_.pricing'
import { Route as AdminNewsletterRouteImport } from './routes/admin_.newsletter'
import { Route as AdminFacebookPostsRouteImport } from './routes/admin_.facebook-posts'
import { Route as AdminEmailTemplatesRouteImport } from './routes/admin_.email-templates'
import { Route as AdminContentFactoryRouteImport } from './routes/admin_.content-factory'
import { Route as AdminCalendarRouteImport } from './routes/admin_.calendar'
import { Route as AdminArticlesRouteImport } from './routes/admin_.articles'
import { Route as ScenarioCreatedCodeRouteImport } from './routes/scenario.created.$code'
import { Route as ApiStripeWebhookRouteImport } from './routes/api/stripe/webhook'
import { Route as ApiPublicTranscribeRouteImport } from './routes/api/public/transcribe'
import { Route as ApiPublicTrackVisitRouteImport } from './routes/api/public/track-visit'
import { Route as ApiPublicSendTestEmailRouteImport } from './routes/api/public/send-test-email'
import { Route as ApiEmailSuppressionRouteImport } from './routes/api/email/suppression'
import { Route as ApiCronQaDailySummaryRouteImport } from './routes/api/cron/qa-daily-summary'
import { Route as AgentScenarioCodeRouteImport } from './routes/agent.scenario.$code'
import { Route as ApiEmailTransactionalSendRouteImport } from './routes/api/email/transactional/send'
import { Route as ApiEmailTransactionalPreviewRouteImport } from './routes/api/email/transactional/preview'
import { Route as ApiEmailQueueProcessRouteImport } from './routes/api/email/queue/process'
import { Route as ApiEmailAuthWebhookRouteImport } from './routes/api/email/auth/webhook'
import { Route as ApiEmailAuthPreviewRouteImport } from './routes/api/email/auth/preview'
import { Route as AgentScenarioCodeEditRouteImport } from './routes/agent.scenario.$code.edit'

const VisitsRoute = VisitsRouteImport.update({
  id: '/visits',
  path: '/visits',
  getParentRoute: () => rootRouteImport,
} as any)
const UsersRoute = UsersRouteImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => rootRouteImport,
} as any)
const UnsubscribeRoute = UnsubscribeRouteImport.update({
  id: '/unsubscribe',
  path: '/unsubscribe',
  getParentRoute: () => rootRouteImport,
} as any)
const TestingRoute = TestingRouteImport.update({
  id: '/testing',
  path: '/testing',
  getParentRoute: () => rootRouteImport,
} as any)
const TasksRoute = TasksRouteImport.update({
  id: '/tasks',
  path: '/tasks',
  getParentRoute: () => rootRouteImport,
} as any)
const StaffRoute = StaffRouteImport.update({
  id: '/staff',
  path: '/staff',
  getParentRoute: () => rootRouteImport,
} as any)
const SourcesRoute = SourcesRouteImport.update({
  id: '/sources',
  path: '/sources',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapInternalDotxmlRoute = SitemapInternalDotxmlRouteImport.update({
  id: '/sitemap-internal.xml',
  path: '/sitemap-internal.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const RegisterRoute = RegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => rootRouteImport,
} as any)
const QaManualRoute = QaManualRouteImport.update({
  id: '/qa-manual',
  path: '/qa-manual',
  getParentRoute: () => rootRouteImport,
} as any)
const QaCreditsRoute = QaCreditsRouteImport.update({
  id: '/qa-credits',
  path: '/qa-credits',
  getParentRoute: () => rootRouteImport,
} as any)
const QaRoute = QaRouteImport.update({
  id: '/qa',
  path: '/qa',
  getParentRoute: () => rootRouteImport,
} as any)
const PricingRoute = PricingRouteImport.update({
  id: '/pricing',
  path: '/pricing',
  getParentRoute: () => rootRouteImport,
} as any)
const NdaRoute = NdaRouteImport.update({
  id: '/nda',
  path: '/nda',
  getParentRoute: () => rootRouteImport,
} as any)
const LegalRoute = LegalRouteImport.update({
  id: '/legal',
  path: '/legal',
  getParentRoute: () => rootRouteImport,
} as any)
const LearningCenterRoute = LearningCenterRouteImport.update({
  id: '/learning-center',
  path: '/learning-center',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AgentRoute = AgentRouteImport.update({
  id: '/agent',
  path: '/agent',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const StaffReportRoute = StaffReportRouteImport.update({
  id: '/staff_/report',
  path: '/staff/report',
  getParentRoute: () => rootRouteImport,
} as any)
const ScenarioNewRoute = ScenarioNewRouteImport.update({
  id: '/scenario/new',
  path: '/scenario/new',
  getParentRoute: () => rootRouteImport,
} as any)
const ScenarioCodeRoute = ScenarioCodeRouteImport.update({
  id: '/scenario/$code',
  path: '/scenario/$code',
  getParentRoute: () => rootRouteImport,
} as any)
const LearningCenterSlugRoute = LearningCenterSlugRouteImport.update({
  id: '/learning-center_/$slug',
  path: '/learning-center/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const EmailUnsubscribeRoute = EmailUnsubscribeRouteImport.update({
  id: '/email/unsubscribe',
  path: '/email/unsubscribe',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthVerifyRoute = AuthVerifyRouteImport.update({
  id: '/verify',
  path: '/verify',
  getParentRoute: () => AuthRoute,
} as any)
const AdminUsersRoute = AdminUsersRouteImport.update({
  id: '/admin_/users',
  path: '/admin/users',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminStaffRoute = AdminStaffRouteImport.update({
  id: '/admin_/staff',
  path: '/admin/staff',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminPricingRoute = AdminPricingRouteImport.update({
  id: '/admin_/pricing',
  path: '/admin/pricing',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminNewsletterRoute = AdminNewsletterRouteImport.update({
  id: '/admin_/newsletter',
  path: '/admin/newsletter',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminFacebookPostsRoute = AdminFacebookPostsRouteImport.update({
  id: '/admin_/facebook-posts',
  path: '/admin/facebook-posts',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminEmailTemplatesRoute = AdminEmailTemplatesRouteImport.update({
  id: '/admin_/email-templates',
  path: '/admin/email-templates',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminContentFactoryRoute = AdminContentFactoryRouteImport.update({
  id: '/admin_/content-factory',
  path: '/admin/content-factory',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminCalendarRoute = AdminCalendarRouteImport.update({
  id: '/admin_/calendar',
  path: '/admin/calendar',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminArticlesRoute = AdminArticlesRouteImport.update({
  id: '/admin_/articles',
  path: '/admin/articles',
  getParentRoute: () => rootRouteImport,
} as any)
const ScenarioCreatedCodeRoute = ScenarioCreatedCodeRouteImport.update({
  id: '/scenario/created/$code',
  path: '/scenario/created/$code',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiStripeWebhookRoute = ApiStripeWebhookRouteImport.update({
  id: '/api/stripe/webhook',
  path: '/api/stripe/webhook',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicTranscribeRoute = ApiPublicTranscribeRouteImport.update({
  id: '/api/public/transcribe',
  path: '/api/public/transcribe',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicTrackVisitRoute = ApiPublicTrackVisitRouteImport.update({
  id: '/api/public/track-visit',
  path: '/api/public/track-visit',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicSendTestEmailRoute = ApiPublicSendTestEmailRouteImport.update({
  id: '/api/public/send-test-email',
  path: '/api/public/send-test-email',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiEmailSuppressionRoute = ApiEmailSuppressionRouteImport.update({
  id: '/api/email/suppression',
  path: '/api/email/suppression',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiCronQaDailySummaryRoute = ApiCronQaDailySummaryRouteImport.update({
  id: '/api/cron/qa-daily-summary',
  path: '/api/cron/qa-daily-summary',
  getParentRoute: () => rootRouteImport,
} as any)
const AgentScenarioCodeRoute = AgentScenarioCodeRouteImport.update({
  id: '/scenario/$code',
  path: '/scenario/$code',
  getParentRoute: () => AgentRoute,
} as any)
const ApiEmailTransactionalSendRoute =
  ApiEmailTransactionalSendRouteImport.update({
    id: '/api/email/transactional/send',
    path: '/api/email/transactional/send',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiEmailTransactionalPreviewRoute =
  ApiEmailTransactionalPreviewRouteImport.update({
    id: '/api/email/transactional/preview',
    path: '/api/email/transactional/preview',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiEmailQueueProcessRoute = ApiEmailQueueProcessRouteImport.update({
  id: '/api/email/queue/process',
  path: '/api/email/queue/process',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiEmailAuthWebhookRoute = ApiEmailAuthWebhookRouteImport.update({
  id: '/api/email/auth/webhook',
  path: '/api/email/auth/webhook',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiEmailAuthPreviewRoute = ApiEmailAuthPreviewRouteImport.update({
  id: '/api/email/auth/preview',
  path: '/api/email/auth/preview',
  getParentRoute: () => rootRouteImport,
} as any)
const AgentScenarioCodeEditRoute = AgentScenarioCodeEditRouteImport.update({
  id: '/edit',
  path: '/edit',
  getParentRoute: () => AgentScenarioCodeRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/admin': typeof AdminRoute
  '/agent': typeof AgentRouteWithChildren
  '/auth': typeof AuthRouteWithChildren
  '/learning-center': typeof LearningCenterRoute
  '/legal': typeof LegalRoute
  '/nda': typeof NdaRoute
  '/pricing': typeof PricingRoute
  '/qa': typeof QaRoute
  '/qa-credits': typeof QaCreditsRoute
  '/qa-manual': typeof QaManualRoute
  '/register': typeof RegisterRoute
  '/reset-password': typeof ResetPasswordRoute
  '/sitemap-internal.xml': typeof SitemapInternalDotxmlRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/sources': typeof SourcesRoute
  '/staff': typeof StaffRoute
  '/tasks': typeof TasksRoute
  '/testing': typeof TestingRoute
  '/unsubscribe': typeof UnsubscribeRoute
  '/users': typeof UsersRoute
  '/visits': typeof VisitsRoute
  '/admin/articles': typeof AdminArticlesRoute
  '/admin/calendar': typeof AdminCalendarRoute
  '/admin/content-factory': typeof AdminContentFactoryRoute
  '/admin/email-templates': typeof AdminEmailTemplatesRoute
  '/admin/facebook-posts': typeof AdminFacebookPostsRoute
  '/admin/newsletter': typeof AdminNewsletterRoute
  '/admin/pricing': typeof AdminPricingRoute
  '/admin/staff': typeof AdminStaffRoute
  '/admin/users': typeof AdminUsersRoute
  '/auth/verify': typeof AuthVerifyRoute
  '/email/unsubscribe': typeof EmailUnsubscribeRoute
  '/learning-center/$slug': typeof LearningCenterSlugRoute
  '/scenario/$code': typeof ScenarioCodeRoute
  '/scenario/new': typeof ScenarioNewRoute
  '/staff/report': typeof StaffReportRoute
  '/agent/scenario/$code': typeof AgentScenarioCodeRouteWithChildren
  '/api/cron/qa-daily-summary': typeof ApiCronQaDailySummaryRoute
  '/api/email/suppression': typeof ApiEmailSuppressionRoute
  '/api/public/send-test-email': typeof ApiPublicSendTestEmailRoute
  '/api/public/track-visit': typeof ApiPublicTrackVisitRoute
  '/api/public/transcribe': typeof ApiPublicTranscribeRoute
  '/api/stripe/webhook': typeof ApiStripeWebhookRoute
  '/scenario/created/$code': typeof ScenarioCreatedCodeRoute
  '/agent/scenario/$code/edit': typeof AgentScenarioCodeEditRoute
  '/api/email/auth/preview': typeof ApiEmailAuthPreviewRoute
  '/api/email/auth/webhook': typeof ApiEmailAuthWebhookRoute
  '/api/email/queue/process': typeof ApiEmailQueueProcessRoute
  '/api/email/transactional/preview': typeof ApiEmailTransactionalPreviewRoute
  '/api/email/transactional/send': typeof ApiEmailTransactionalSendRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/admin': typeof AdminRoute
  '/agent': typeof AgentRouteWithChildren
  '/auth': typeof AuthRouteWithChildren
  '/learning-center': typeof LearningCenterRoute
  '/legal': typeof LegalRoute
  '/nda': typeof NdaRoute
  '/pricing': typeof PricingRoute
  '/qa': typeof QaRoute
  '/qa-credits': typeof QaCreditsRoute
  '/qa-manual': typeof QaManualRoute
  '/register': typeof RegisterRoute
  '/reset-password': typeof ResetPasswordRoute
  '/sitemap-internal.xml': typeof SitemapInternalDotxmlRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/sources': typeof SourcesRoute
  '/staff': typeof StaffRoute
  '/tasks': typeof TasksRoute
  '/testing': typeof TestingRoute
  '/unsubscribe': typeof UnsubscribeRoute
  '/users': typeof UsersRoute
  '/visits': typeof VisitsRoute
  '/admin/articles': typeof AdminArticlesRoute
  '/admin/calendar': typeof AdminCalendarRoute
  '/admin/content-factory': typeof AdminContentFactoryRoute
  '/admin/email-templates': typeof AdminEmailTemplatesRoute
  '/admin/facebook-posts': typeof AdminFacebookPostsRoute
  '/admin/newsletter': typeof AdminNewsletterRoute
  '/admin/pricing': typeof AdminPricingRoute
  '/admin/staff': typeof AdminStaffRoute
  '/admin/users': typeof AdminUsersRoute
  '/auth/verify': typeof AuthVerifyRoute
  '/email/unsubscribe': typeof EmailUnsubscribeRoute
  '/learning-center/$slug': typeof LearningCenterSlugRoute
  '/scenario/$code': typeof ScenarioCodeRoute
  '/scenario/new': typeof ScenarioNewRoute
  '/staff/report': typeof StaffReportRoute
  '/agent/scenario/$code': typeof AgentScenarioCodeRouteWithChildren
  '/api/cron/qa-daily-summary': typeof ApiCronQaDailySummaryRoute
  '/api/email/suppression': typeof ApiEmailSuppressionRoute
  '/api/public/send-test-email': typeof ApiPublicSendTestEmailRoute
  '/api/public/track-visit': typeof ApiPublicTrackVisitRoute
  '/api/public/transcribe': typeof ApiPublicTranscribeRoute
  '/api/stripe/webhook': typeof ApiStripeWebhookRoute
  '/scenario/created/$code': typeof ScenarioCreatedCodeRoute
  '/agent/scenario/$code/edit': typeof AgentScenarioCodeEditRoute
  '/api/email/auth/preview': typeof ApiEmailAuthPreviewRoute
  '/api/email/auth/webhook': typeof ApiEmailAuthWebhookRoute
  '/api/email/queue/process': typeof ApiEmailQueueProcessRoute
  '/api/email/transactional/preview': typeof ApiEmailTransactionalPreviewRoute
  '/api/email/transactional/send': typeof ApiEmailTransactionalSendRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/admin': typeof AdminRoute
  '/agent': typeof AgentRouteWithChildren
  '/auth': typeof AuthRouteWithChildren
  '/learning-center': typeof LearningCenterRoute
  '/legal': typeof LegalRoute
  '/nda': typeof NdaRoute
  '/pricing': typeof PricingRoute
  '/qa': typeof QaRoute
  '/qa-credits': typeof QaCreditsRoute
  '/qa-manual': typeof QaManualRoute
  '/register': typeof RegisterRoute
  '/reset-password': typeof ResetPasswordRoute
  '/sitemap-internal.xml': typeof SitemapInternalDotxmlRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/sources': typeof SourcesRoute
  '/staff': typeof StaffRoute
  '/tasks': typeof TasksRoute
  '/testing': typeof TestingRoute
  '/unsubscribe': typeof UnsubscribeRoute
  '/users': typeof UsersRoute
  '/visits': typeof VisitsRoute
  '/admin_/articles': typeof AdminArticlesRoute
  '/admin_/calendar': typeof AdminCalendarRoute
  '/admin_/content-factory': typeof AdminContentFactoryRoute
  '/admin_/email-templates': typeof AdminEmailTemplatesRoute
  '/admin_/facebook-posts': typeof AdminFacebookPostsRoute
  '/admin_/newsletter': typeof AdminNewsletterRoute
  '/admin_/pricing': typeof AdminPricingRoute
  '/admin_/staff': typeof AdminStaffRoute
  '/admin_/users': typeof AdminUsersRoute
  '/auth/verify': typeof AuthVerifyRoute
  '/email/unsubscribe': typeof EmailUnsubscribeRoute
  '/learning-center_/$slug': typeof LearningCenterSlugRoute
  '/scenario/$code': typeof ScenarioCodeRoute
  '/scenario/new': typeof ScenarioNewRoute
  '/staff_/report': typeof StaffReportRoute
  '/agent/scenario/$code': typeof AgentScenarioCodeRouteWithChildren
  '/api/cron/qa-daily-summary': typeof ApiCronQaDailySummaryRoute
  '/api/email/suppression': typeof ApiEmailSuppressionRoute
  '/api/public/send-test-email': typeof ApiPublicSendTestEmailRoute
  '/api/public/track-visit': typeof ApiPublicTrackVisitRoute
  '/api/public/transcribe': typeof ApiPublicTranscribeRoute
  '/api/stripe/webhook': typeof ApiStripeWebhookRoute
  '/scenario/created/$code': typeof ScenarioCreatedCodeRoute
  '/agent/scenario/$code/edit': typeof AgentScenarioCodeEditRoute
  '/api/email/auth/preview': typeof ApiEmailAuthPreviewRoute
  '/api/email/auth/webhook': typeof ApiEmailAuthWebhookRoute
  '/api/email/queue/process': typeof ApiEmailQueueProcessRoute
  '/api/email/transactional/preview': typeof ApiEmailTransactionalPreviewRoute
  '/api/email/transactional/send': typeof ApiEmailTransactionalSendRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/admin'
    | '/agent'
    | '/auth'
    | '/learning-center'
    | '/legal'
    | '/nda'
    | '/pricing'
    | '/qa'
    | '/qa-credits'
    | '/qa-manual'
    | '/register'
    | '/reset-password'
    | '/sitemap-internal.xml'
    | '/sitemap.xml'
    | '/sources'
    | '/staff'
    | '/tasks'
    | '/testing'
    | '/unsubscribe'
    | '/users'
    | '/visits'
    | '/admin/articles'
    | '/admin/calendar'
    | '/admin/content-factory'
    | '/admin/email-templates'
    | '/admin/facebook-posts'
    | '/admin/newsletter'
    | '/admin/pricing'
    | '/admin/staff'
    | '/admin/users'
    | '/auth/verify'
    | '/email/unsubscribe'
    | '/learning-center/$slug'
    | '/scenario/$code'
    | '/scenario/new'
    | '/staff/report'
    | '/agent/scenario/$code'
    | '/api/cron/qa-daily-summary'
    | '/api/email/suppression'
    | '/api/public/send-test-email'
    | '/api/public/track-visit'
    | '/api/public/transcribe'
    | '/api/stripe/webhook'
    | '/scenario/created/$code'
    | '/agent/scenario/$code/edit'
    | '/api/email/auth/preview'
    | '/api/email/auth/webhook'
    | '/api/email/queue/process'
    | '/api/email/transactional/preview'
    | '/api/email/transactional/send'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/admin'
    | '/agent'
    | '/auth'
    | '/learning-center'
    | '/legal'
    | '/nda'
    | '/pricing'
    | '/qa'
    | '/qa-credits'
    | '/qa-manual'
    | '/register'
    | '/reset-password'
    | '/sitemap-internal.xml'
    | '/sitemap.xml'
    | '/sources'
    | '/staff'
    | '/tasks'
    | '/testing'
    | '/unsubscribe'
    | '/users'
    | '/visits'
    | '/admin/articles'
    | '/admin/calendar'
    | '/admin/content-factory'
    | '/admin/email-templates'
    | '/admin/facebook-posts'
    | '/admin/newsletter'
    | '/admin/pricing'
    | '/admin/staff'
    | '/admin/users'
    | '/auth/verify'
    | '/email/unsubscribe'
    | '/learning-center/$slug'
    | '/scenario/$code'
    | '/scenario/new'
    | '/staff/report'
    | '/agent/scenario/$code'
    | '/api/cron/qa-daily-summary'
    | '/api/email/suppression'
    | '/api/public/send-test-email'
    | '/api/public/track-visit'
    | '/api/public/transcribe'
    | '/api/stripe/webhook'
    | '/scenario/created/$code'
    | '/agent/scenario/$code/edit'
    | '/api/email/auth/preview'
    | '/api/email/auth/webhook'
    | '/api/email/queue/process'
    | '/api/email/transactional/preview'
    | '/api/email/transactional/send'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/admin'
    | '/agent'
    | '/auth'
    | '/learning-center'
    | '/legal'
    | '/nda'
    | '/pricing'
    | '/qa'
    | '/qa-credits'
    | '/qa-manual'
    | '/register'
    | '/reset-password'
    | '/sitemap-internal.xml'
    | '/sitemap.xml'
    | '/sources'
    | '/staff'
    | '/tasks'
    | '/testing'
    | '/unsubscribe'
    | '/users'
    | '/visits'
    | '/admin_/articles'
    | '/admin_/calendar'
    | '/admin_/content-factory'
    | '/admin_/email-templates'
    | '/admin_/facebook-posts'
    | '/admin_/newsletter'
    | '/admin_/pricing'
    | '/admin_/staff'
    | '/admin_/users'
    | '/auth/verify'
    | '/email/unsubscribe'
    | '/learning-center_/$slug'
    | '/scenario/$code'
    | '/scenario/new'
    | '/staff_/report'
    | '/agent/scenario/$code'
    | '/api/cron/qa-daily-summary'
    | '/api/email/suppression'
    | '/api/public/send-test-email'
    | '/api/public/track-visit'
    | '/api/public/transcribe'
    | '/api/stripe/webhook'
    | '/scenario/created/$code'
    | '/agent/scenario/$code/edit'
    | '/api/email/auth/preview'
    | '/api/email/auth/webhook'
    | '/api/email/queue/process'
    | '/api/email/transactional/preview'
    | '/api/email/transactional/send'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  AdminRoute: typeof AdminRoute
  AgentRoute: typeof AgentRouteWithChildren
  AuthRoute: typeof AuthRouteWithChildren
  LearningCenterRoute: typeof LearningCenterRoute
  LegalRoute: typeof LegalRoute
  NdaRoute: typeof NdaRoute
  PricingRoute: typeof PricingRoute
  QaRoute: typeof QaRoute
  QaCreditsRoute: typeof QaCreditsRoute
  QaManualRoute: typeof QaManualRoute
  RegisterRoute: typeof RegisterRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  SitemapInternalDotxmlRoute: typeof SitemapInternalDotxmlRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  SourcesRoute: typeof SourcesRoute
  StaffRoute: typeof StaffRoute
  TasksRoute: typeof TasksRoute
  TestingRoute: typeof TestingRoute
  UnsubscribeRoute: typeof UnsubscribeRoute
  UsersRoute: typeof UsersRoute
  VisitsRoute: typeof VisitsRoute
  AdminArticlesRoute: typeof AdminArticlesRoute
  AdminCalendarRoute: typeof AdminCalendarRoute
  AdminContentFactoryRoute: typeof AdminContentFactoryRoute
  AdminEmailTemplatesRoute: typeof AdminEmailTemplatesRoute
  AdminFacebookPostsRoute: typeof AdminFacebookPostsRoute
  AdminNewsletterRoute: typeof AdminNewsletterRoute
  AdminPricingRoute: typeof AdminPricingRoute
  AdminStaffRoute: typeof AdminStaffRoute
  AdminUsersRoute: typeof AdminUsersRoute
  EmailUnsubscribeRoute: typeof EmailUnsubscribeRoute
  LearningCenterSlugRoute: typeof LearningCenterSlugRoute
  ScenarioCodeRoute: typeof ScenarioCodeRoute
  ScenarioNewRoute: typeof ScenarioNewRoute
  StaffReportRoute: typeof StaffReportRoute
  ApiCronQaDailySummaryRoute: typeof ApiCronQaDailySummaryRoute
  ApiEmailSuppressionRoute: typeof ApiEmailSuppressionRoute
  ApiPublicSendTestEmailRoute: typeof ApiPublicSendTestEmailRoute
  ApiPublicTrackVisitRoute: typeof ApiPublicTrackVisitRoute
  ApiPublicTranscribeRoute: typeof ApiPublicTranscribeRoute
  ApiStripeWebhookRoute: typeof ApiStripeWebhookRoute
  ScenarioCreatedCodeRoute: typeof ScenarioCreatedCodeRoute
  ApiEmailAuthPreviewRoute: typeof ApiEmailAuthPreviewRoute
  ApiEmailAuthWebhookRoute: typeof ApiEmailAuthWebhookRoute
  ApiEmailQueueProcessRoute: typeof ApiEmailQueueProcessRoute
  ApiEmailTransactionalPreviewRoute: typeof ApiEmailTransactionalPreviewRoute
  ApiEmailTransactionalSendRoute: typeof ApiEmailTransactionalSendRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/visits': {
      id: '/visits'
      path: '/visits'
      fullPath: '/visits'
      preLoaderRoute: typeof VisitsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/users': {
      id: '/users'
      path: '/users'
      fullPath: '/users'
      preLoaderRoute: typeof UsersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/unsubscribe': {
      id: '/unsubscribe'
      path: '/unsubscribe'
      fullPath: '/unsubscribe'
      preLoaderRoute: typeof UnsubscribeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/testing': {
      id: '/testing'
      path: '/testing'
      fullPath: '/testing'
      preLoaderRoute: typeof TestingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tasks': {
      id: '/tasks'
      path: '/tasks'
      fullPath: '/tasks'
      preLoaderRoute: typeof TasksRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/staff': {
      id: '/staff'
      path: '/staff'
      fullPath: '/staff'
      preLoaderRoute: typeof StaffRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sources': {
      id: '/sources'
      path: '/sources'
      fullPath: '/sources'
      preLoaderRoute: typeof SourcesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap-internal.xml': {
      id: '/sitemap-internal.xml'
      path: '/sitemap-internal.xml'
      fullPath: '/sitemap-internal.xml'
      preLoaderRoute: typeof SitemapInternalDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/register': {
      id: '/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof RegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/qa-manual': {
      id: '/qa-manual'
      path: '/qa-manual'
      fullPath: '/qa-manual'
      preLoaderRoute: typeof QaManualRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/qa-credits': {
      id: '/qa-credits'
      path: '/qa-credits'
      fullPath: '/qa-credits'
      preLoaderRoute: typeof QaCreditsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/qa': {
      id: '/qa'
      path: '/qa'
      fullPath: '/qa'
      preLoaderRoute: typeof QaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pricing': {
      id: '/pricing'
      path: '/pricing'
      fullPath: '/pricing'
      preLoaderRoute: typeof PricingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/nda': {
      id: '/nda'
      path: '/nda'
      fullPath: '/nda'
      preLoaderRoute: typeof NdaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/legal': {
      id: '/legal'
      path: '/legal'
      fullPath: '/legal'
      preLoaderRoute: typeof LegalRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/learning-center': {
      id: '/learning-center'
      path: '/learning-center'
      fullPath: '/learning-center'
      preLoaderRoute: typeof LearningCenterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/agent': {
      id: '/agent'
      path: '/agent'
      fullPath: '/agent'
      preLoaderRoute: typeof AgentRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/staff_/report': {
      id: '/staff_/report'
      path: '/staff/report'
      fullPath: '/staff/report'
      preLoaderRoute: typeof StaffReportRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/scenario/new': {
      id: '/scenario/new'
      path: '/scenario/new'
      fullPath: '/scenario/new'
      preLoaderRoute: typeof ScenarioNewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/scenario/$code': {
      id: '/scenario/$code'
      path: '/scenario/$code'
      fullPath: '/scenario/$code'
      preLoaderRoute: typeof ScenarioCodeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/learning-center_/$slug': {
      id: '/learning-center_/$slug'
      path: '/learning-center/$slug'
      fullPath: '/learning-center/$slug'
      preLoaderRoute: typeof LearningCenterSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/email/unsubscribe': {
      id: '/email/unsubscribe'
      path: '/email/unsubscribe'
      fullPath: '/email/unsubscribe'
      preLoaderRoute: typeof EmailUnsubscribeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/verify': {
      id: '/auth/verify'
      path: '/verify'
      fullPath: '/auth/verify'
      preLoaderRoute: typeof AuthVerifyRouteImport
      parentRoute: typeof AuthRoute
    }
    '/admin_/users': {
      id: '/admin_/users'
      path: '/admin/users'
      fullPath: '/admin/users'
      preLoaderRoute: typeof AdminUsersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin_/staff': {
      id: '/admin_/staff'
      path: '/admin/staff'
      fullPath: '/admin/staff'
      preLoaderRoute: typeof AdminStaffRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin_/pricing': {
      id: '/admin_/pricing'
      path: '/admin/pricing'
      fullPath: '/admin/pricing'
      preLoaderRoute: typeof AdminPricingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin_/newsletter': {
      id: '/admin_/newsletter'
      path: '/admin/newsletter'
      fullPath: '/admin/newsletter'
      preLoaderRoute: typeof AdminNewsletterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin_/facebook-posts': {
      id: '/admin_/facebook-posts'
      path: '/admin/facebook-posts'
      fullPath: '/admin/facebook-posts'
      preLoaderRoute: typeof AdminFacebookPostsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin_/email-templates': {
      id: '/admin_/email-templates'
      path: '/admin/email-templates'
      fullPath: '/admin/email-templates'
      preLoaderRoute: typeof AdminEmailTemplatesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin_/content-factory': {
      id: '/admin_/content-factory'
      path: '/admin/content-factory'
      fullPath: '/admin/content-factory'
      preLoaderRoute: typeof AdminContentFactoryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin_/calendar': {
      id: '/admin_/calendar'
      path: '/admin/calendar'
      fullPath: '/admin/calendar'
      preLoaderRoute: typeof AdminCalendarRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin_/articles': {
      id: '/admin_/articles'
      path: '/admin/articles'
      fullPath: '/admin/articles'
      preLoaderRoute: typeof AdminArticlesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/scenario/created/$code': {
      id: '/scenario/created/$code'
      path: '/scenario/created/$code'
      fullPath: '/scenario/created/$code'
      preLoaderRoute: typeof ScenarioCreatedCodeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/stripe/webhook': {
      id: '/api/stripe/webhook'
      path: '/api/stripe/webhook'
      fullPath: '/api/stripe/webhook'
      preLoaderRoute: typeof ApiStripeWebhookRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/transcribe': {
      id: '/api/public/transcribe'
      path: '/api/public/transcribe'
      fullPath: '/api/public/transcribe'
      preLoaderRoute: typeof ApiPublicTranscribeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/track-visit': {
      id: '/api/public/track-visit'
      path: '/api/public/track-visit'
      fullPath: '/api/public/track-visit'
      preLoaderRoute: typeof ApiPublicTrackVisitRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/send-test-email': {
      id: '/api/public/send-test-email'
      path: '/api/public/send-test-email'
      fullPath: '/api/public/send-test-email'
      preLoaderRoute: typeof ApiPublicSendTestEmailRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/email/suppression': {
      id: '/api/email/suppression'
      path: '/api/email/suppression'
      fullPath: '/api/email/suppression'
      preLoaderRoute: typeof ApiEmailSuppressionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/cron/qa-daily-summary': {
      id: '/api/cron/qa-daily-summary'
      path: '/api/cron/qa-daily-summary'
      fullPath: '/api/cron/qa-daily-summary'
      preLoaderRoute: typeof ApiCronQaDailySummaryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/agent/scenario/$code': {
      id: '/agent/scenario/$code'
      path: '/scenario/$code'
      fullPath: '/agent/scenario/$code'
      preLoaderRoute: typeof AgentScenarioCodeRouteImport
      parentRoute: typeof AgentRoute
    }
    '/api/email/transactional/send': {
      id: '/api/email/transactional/send'
      path: '/api/email/transactional/send'
      fullPath: '/api/email/transactional/send'
      preLoaderRoute: typeof ApiEmailTransactionalSendRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/email/transactional/preview': {
      id: '/api/email/transactional/preview'
      path: '/api/email/transactional/preview'
      fullPath: '/api/email/transactional/preview'
      preLoaderRoute: typeof ApiEmailTransactionalPreviewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/email/queue/process': {
      id: '/api/email/queue/process'
      path: '/api/email/queue/process'
      fullPath: '/api/email/queue/process'
      preLoaderRoute: typeof ApiEmailQueueProcessRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/email/auth/webhook': {
      id: '/api/email/auth/webhook'
      path: '/api/email/auth/webhook'
      fullPath: '/api/email/auth/webhook'
      preLoaderRoute: typeof ApiEmailAuthWebhookRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/email/auth/preview': {
      id: '/api/email/auth/preview'
      path: '/api/email/auth/preview'
      fullPath: '/api/email/auth/preview'
      preLoaderRoute: typeof ApiEmailAuthPreviewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/agent/scenario/$code/edit': {
      id: '/agent/scenario/$code/edit'
      path: '/edit'
      fullPath: '/agent/scenario/$code/edit'
      preLoaderRoute: typeof AgentScenarioCodeEditRouteImport
      parentRoute: typeof AgentScenarioCodeRoute
    }
  }
}

interface AgentScenarioCodeRouteChildren {
  AgentScenarioCodeEditRoute: typeof AgentScenarioCodeEditRoute
}

const AgentScenarioCodeRouteChildren: AgentScenarioCodeRouteChildren = {
  AgentScenarioCodeEditRoute: AgentScenarioCodeEditRoute,
}

const AgentScenarioCodeRouteWithChildren =
  AgentScenarioCodeRoute._addFileChildren(AgentScenarioCodeRouteChildren)

interface AgentRouteChildren {
  AgentScenarioCodeRoute: typeof AgentScenarioCodeRouteWithChildren
}

const AgentRouteChildren: AgentRouteChildren = {
  AgentScenarioCodeRoute: AgentScenarioCodeRouteWithChildren,
}

const AgentRouteWithChildren = AgentRoute._addFileChildren(AgentRouteChildren)

interface AuthRouteChildren {
  AuthVerifyRoute: typeof AuthVerifyRoute
}

const AuthRouteChildren: AuthRouteChildren = {
  AuthVerifyRoute: AuthVerifyRoute,
}

const AuthRouteWithChildren = AuthRoute._addFileChildren(AuthRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  AdminRoute: AdminRoute,
  AgentRoute: AgentRouteWithChildren,
  AuthRoute: AuthRouteWithChildren,
  LearningCenterRoute: LearningCenterRoute,
  LegalRoute: LegalRoute,
  NdaRoute: NdaRoute,
  PricingRoute: PricingRoute,
  QaRoute: QaRoute,
  QaCreditsRoute: QaCreditsRoute,
  QaManualRoute: QaManualRoute,
  RegisterRoute: RegisterRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  SitemapInternalDotxmlRoute: SitemapInternalDotxmlRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  SourcesRoute: SourcesRoute,
  StaffRoute: StaffRoute,
  TasksRoute: TasksRoute,
  TestingRoute: TestingRoute,
  UnsubscribeRoute: UnsubscribeRoute,
  UsersRoute: UsersRoute,
  VisitsRoute: VisitsRoute,
  AdminArticlesRoute: AdminArticlesRoute,
  AdminCalendarRoute: AdminCalendarRoute,
  AdminContentFactoryRoute: AdminContentFactoryRoute,
  AdminEmailTemplatesRoute: AdminEmailTemplatesRoute,
  AdminFacebookPostsRoute: AdminFacebookPostsRoute,
  AdminNewsletterRoute: AdminNewsletterRoute,
  AdminPricingRoute: AdminPricingRoute,
  AdminStaffRoute: AdminStaffRoute,
  AdminUsersRoute: AdminUsersRoute,
  EmailUnsubscribeRoute: EmailUnsubscribeRoute,
  LearningCenterSlugRoute: LearningCenterSlugRoute,
  ScenarioCodeRoute: ScenarioCodeRoute,
  ScenarioNewRoute: ScenarioNewRoute,
  StaffReportRoute: StaffReportRoute,
  ApiCronQaDailySummaryRoute: ApiCronQaDailySummaryRoute,
  ApiEmailSuppressionRoute: ApiEmailSuppressionRoute,
  ApiPublicSendTestEmailRoute: ApiPublicSendTestEmailRoute,
  ApiPublicTrackVisitRoute: ApiPublicTrackVisitRoute,
  ApiPublicTranscribeRoute: ApiPublicTranscribeRoute,
  ApiStripeWebhookRoute: ApiStripeWebhookRoute,
  ScenarioCreatedCodeRoute: ScenarioCreatedCodeRoute,
  ApiEmailAuthPreviewRoute: ApiEmailAuthPreviewRoute,
  ApiEmailAuthWebhookRoute: ApiEmailAuthWebhookRoute,
  ApiEmailQueueProcessRoute: ApiEmailQueueProcessRoute,
  ApiEmailTransactionalPreviewRoute: ApiEmailTransactionalPreviewRoute,
  ApiEmailTransactionalSendRoute: ApiEmailTransactionalSendRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
