// This file is automatically generated. Do not edit it directly.
import { createMiddleware } from '@tanstack/react-start'
import { getRequest } from '@tanstack/react-start/server'
import { createClient } from '@supabase/supabase-js'
import type { Database } from './types'

export const requireSupabaseAuth = createMiddleware({ type: 'function' }).server(
  async ({ next }) => {
    let url = typeof process !== "undefined" ? process.env.SUPABASE_URL : undefined;
    let key = typeof process !== "undefined" ? process.env.SUPABASE_PUBLISHABLE_KEY : undefined;

    try {
      const storageKey = Symbol.for("tanstack-start:event-storage");
      const storage = (globalThis as Record<symbol, any>)[storageKey];
      const store = storage?.getStore();
      const event = store?.h3Event;
      const env = (event?.context as { cloudflare?: { env?: Record<string, unknown> } })?.cloudflare?.env;
      if (env) {
        if (typeof env.SUPABASE_URL === "string") {
          url = url || env.SUPABASE_URL;
        }
        if (typeof env.SUPABASE_PUBLISHABLE_KEY === "string") {
          key = key || env.SUPABASE_PUBLISHABLE_KEY;
        }
      }
    } catch {}

    const SUPABASE_URL = url;
    const SUPABASE_PUBLISHABLE_KEY = key;

    if (!SUPABASE_URL || !SUPABASE_PUBLISHABLE_KEY) {
      const missing = [
        ...(!SUPABASE_URL ? ['SUPABASE_URL'] : []),
        ...(!SUPABASE_PUBLISHABLE_KEY ? ['SUPABASE_PUBLISHABLE_KEY'] : []),
      ];
      const message = `Missing Supabase environment variable(s): ${missing.join(', ')}. Connect Supabase in Lovable Cloud.`;
      console.error(`[Supabase] ${message}`);
      throw new Error(message);
    }
    
    const request = getRequest();

    if (!request?.headers) {
      throw new Error('Unauthorized: No request headers available');
    }

    const authHeader = request.headers.get('authorization');

    if (!authHeader) {
      throw new Error('Unauthorized: No authorization header provided');
    }

    if (!authHeader.startsWith('Bearer ')) {
      throw new Error('Unauthorized: Only Bearer tokens are supported');
    }

    const token = authHeader.replace('Bearer ', '');
    if (!token) {
      throw new Error('Unauthorized: No token provided');
    }

    const supabase = createClient<Database>(
      SUPABASE_URL!,
      SUPABASE_PUBLISHABLE_KEY!,
      {
        global: {
          headers: {
            Authorization: `Bearer ${token}`,
          },
        },
        auth: {
          storage: undefined,
          persistSession: false,
          autoRefreshToken: false,
        },
      }
    );

    const { data, error } = await supabase.auth.getClaims(token);
    if (error || !data?.claims) {
      throw new Error('Unauthorized: Invalid token');
    }

    if (!data.claims.sub) {
      throw new Error('Unauthorized: No user ID found in token');
    }

    return next({
      context: {
        supabase,
        userId: data.claims.sub,
        claims: data.claims,
      },
    });
  },
);
