// This file is automatically generated. Do not edit it directly.
import { createMiddleware } from "@tanstack/react-start";
import { getRequest } from "@tanstack/react-start/server";
import { isLocalDevEnvironment } from "@/lib/env";

export const requireSupabaseAuth = createMiddleware({ type: "function" }).server(
  async ({ next }) => {
    const request = getRequest();

    if (!request?.headers) {
      throw new Error("Unauthorized: No request headers available");
    }

    const authHeader = request.headers.get("authorization");

    if (!authHeader) {
      throw new Error("Unauthorized: No authorization header provided");
    }

    if (!authHeader.startsWith("Bearer ")) {
      throw new Error("Unauthorized: Only Bearer tokens are supported");
    }

    const token = authHeader.replace("Bearer ", "");
    if (!token) {
      throw new Error("Unauthorized: No token provided");
    }

    const { supabaseAdmin } = await import("@/integrations/supabase/client.server");
    const { data, error } = await supabaseAdmin.auth.getUser(token);
    if (error || !data.user) {
      if (isLocalDevEnvironment() && error?.message) {
        console.error("[requireSupabaseAuth] getUser failed:", error.message);
      }
      const detail = isLocalDevEnvironment() && error?.message ? `: ${error.message}` : "";
      throw new Error(`Unauthorized: Invalid token${detail}`);
    }

    return next({
      context: {
        userId: data.user.id,
      },
    });
  },
);
